default: install

install:
	ln -s "${PWD}/vim" "${HOME}/.vim"
	ln -s "${PWD}/zsh" "${HOME}/.zsh"
	ln -s "${PWD}/gemrc" "${HOME}/.gemrc"
	ln -s "${PWD}/gitconfig" "${HOME}/.gitconfig"
	ln -s "${PWD}/gvimrc" "${HOME}/.gvimrc"
	ln -s "${PWD}/muttrc" "${HOME}/.muttrc"
	ln -s "${PWD}/pryrc" "${HOME}/.pryrc"
	ln -s "${PWD}/vimrc" "${HOME}/.vimrc"
	ln -s "${PWD}/xinitrc" "${HOME}/.xinitrc"
	ln -s "${PWD}/Xresources" "${HOME}/.Xresources"
	ln -s "${PWD}/zprofile" "${HOME}/.zprofile"
	ln -s "${PWD}/zshenv" "${HOME}/.zshenv"
	ln -s "${PWD}/zshrc" "${HOME}/.zshrc"
	mkdir -p "${HOME}/bin"
	cp "${PWD}/bin/open" "${HOME}/bin"
	cp "${PWD}/bin/wallpaper" "${HOME}/bin"
	cp "${PWD}/bin/statusbar" "${HOME}/bin"

remove:
	rm -ri "${HOME}/.vim"
	rm -ri "${HOME}/.zsh"
	rm -ri "${HOME}/.gemrc"
	rm -ri "${HOME}/.gitconfig"
	rm -ri "${HOME}/.gvimrc"
	rm -ri "${HOME}/.muttrc"
	rm -ri "${HOME}/.pryrc"
	rm -ri "${HOME}/.vimrc"
	rm -ri "${HOME}/.xinitrc"
	rm -ri "${HOME}/.Xresources"
	rm -ri "${HOME}/.zprofile"
	rm -ri "${HOME}/.zshenv"
	rm -ri "${HOME}/.zshrc"
	rm -ri "${HOME}/bin/open"
	rm -ri "${HOME}/bin/wallpaper"
	rm -ri "${HOME}/bin/statusbar"

