#!/bin/sh
# setup - Setup script for dotfiles

# Helpers
esc="\033["
msg(){ echo -e "${esc}32m✓${esc}m $1"; }
err(){ echo -e "${esc}31m✗${esc}m $1"; }
ask(){
  echo -en "${esc}34m?${esc}m $1"
  if [ "$2" == "y" ]; then
    local ans
    read -sn1 ans
    echo
    [ "$ans" == y -o "$ans" == Y ] && return 0 || return 1
  else
    read -sn1 $2
    echo
  fi
}

# Prepare
set -e
type git &>/dev/null || (err "git is required"; exit 1)
all_mode=""

# Link a file
link_file(){
  local dst="${2/"$HOME"/"~"}"
  local mode=""

  if [ -e "$2" ]; then
    # Set mode
    if [ -z "$all_mode" ]; then
      ask "$dst already exists. [s]kip, [S]kip all, [o]verwrite, \
[O]verwrite all, [b]ackup or [B]ackup all? " mode
      case "$mode" in
        S) all_mode=skip ;;
        O) all_mode=overwr ;;
        B) all_mode=backup ;;
      esac
    fi

    # Handle existing files
    if [ "$all_mode" == skip -o "$mode" == s ]; then
      msg "skipping $dst"
      return
    elif [ "$all_mode" == overwr -o "$mode" == o ]; then
      rm -rf "$2" || err "cannot remove $dst"
    elif [ "$all_mode" == backup -o "$mode" == b ]; then
      mv "$2" "${2}.backup" || err "cannot move $dst"
    fi
  fi

  # Link file
  mkdir -p "$(dirname "$2")"
  ln -s "$1" "$2" && msg "linked $dst" || err "cannot link to $dst"
}

# Iterate trough files
install_files(){
  local files=$(find . -regextype posix-egrep \
    -regex './(\.git.*|setup|README.md)' \
    -prune -o -type f -print | sed 'st^./tt')
  for file in $files; do
    if [ "$(dirname "$file")" == bin ]; then
      link_file "$(realpath "$file")" "$HOME/$file"
    else
      link_file "$(realpath "$file")" "$HOME/.$file"
    fi
  done
}

post_install(){
  # Set up hook
  hook="$DOT/.git/hooks/post-merge"
  if [ \! -e "$hook" ] && ask "Set up git post-merge hook? [y/N] " y; then
    ln -s "$(realpath "$0")" "$hook" &&
      msg "linked $0 to .git/hooks/post-merge" || err "cannot link $0"
  fi

  # Install Vundle
  if ask "Install Vundle.vim? [y/N] " y; then
    git clone https://github.com/gmarik/Vundle.vim.git \
      "$HOME/.vim/bundle/Vundle.vim"
    vim +VundleInstall +qall
  fi
}

# Source directory
DOT="$(dirname "$(realpath "$0")")"
cd "$DOT"

# Hook mode
[ "$GIT_DIR" ] && all_mode=skip

# Run installation
install_files
[ "$GIT_DIR" ] || post_install

