PATH="$HOME/bin:$PATH"
NODE_PATH="/usr/local/lib/node_modules"
EDITOR='vim'
VISUAL='subl3 -w'
BROWSER='open'
PAGER='less'
LESS='-R'
LC_CTYPE=$LANG

export PATH NODE_PATH EDITOR VISUAL BROWSER PAGER LESS LC_CTYPE

