#!/bin/sh

# Window style
bspc config border_width          2
bspc config window_gap            12

# Desktop properties
bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

# Montiors
bspc monitor -d                   i ii iii iv
bspc monitor VGA1 -d              v vi vii viii

# Rules
bspc rule -a feh                  floating=true
bspc rule -a mpv                  floating=true
bspc rule -a Chromium             floating=true
bspc rule -a SshAskpass           floating=true center=true follow=true
bspc rule -a xfontsel             floating=true
bspc rule -a lxappearance         floating=true

