#!/bin/sh

# Window style
bspc config border_width          2
bspc config window_gap            12

# Montiors
bspc monitor -d                   term www iii iv
bspc monitor VGA1 -d              subl vi vii viii

# Desktop properties
bspc config top_padding           16
bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

# Rules
echo Chromium feh mpv |
  xargs -I% bspc rule -a % floating=true

# Panel
~/.config/bspwm/panel &

